include:
- docs/python/_static
- docs/python/_sources
- docs/python/_modules
- docs/python/_static/doctools.js
- docs/python/_static/searchtools.js
- docs/python/_static/language_data.js
- docs/python/_static/documentation_options.js
- docs/python/_static/file.png
- docs/python/_static/jquery.js
- docs/python/_static/underscore.js
- docs/python/_static/underscore-1.13.1.js
- docs/python/_static/alabaster.css
- docs/python/_static/pygments.css
- docs/python/_static/minus.png
- docs/python/_static/basic.css
- docs/python/_static/jquery-3.5.1.js
- docs/python/_static/plus.png
- docs/python/_static/custom.css
- docs/python/_sources/index.rst.txt
- docs/python/_sources/apidoc
- docs/python/_sources/apidoc/mcap.mcap0.opcode.rst.txt
- docs/python/_sources/apidoc/mcap.mcap0.chunk_builder.rst.txt
- docs/python/_sources/apidoc/index.rst.txt
- docs/python/_sources/apidoc/mcap.mcap0.writer.rst.txt
- docs/python/_sources/apidoc/mcap.rst.txt
- docs/python/_sources/apidoc/mcap.mcap0.rst.txt
- docs/python/_sources/apidoc/mcap.mcap0.serialization.rst.txt
- docs/python/_sources/apidoc/mcap.mcap0.exceptions.rst.txt
- docs/python/_sources/apidoc/mcap.mcap0.records.rst.txt
- docs/python/_sources/apidoc/mcap.mcap0.stream_reader.rst.txt
- docs/python/_sources/apidoc/mcap.mcap0.data_stream.rst.txt
- docs/python/_modules/index.html
- docs/python/_modules/mcap
- docs/python/_modules/mcap/mcap0
- docs/python/_modules/mcap/mcap0/exceptions.html
- docs/python/_modules/mcap/mcap0/stream_reader.html
- docs/python/_modules/mcap/mcap0/writer.html
- docs/python/_modules/mcap/mcap0/serialization.html
- docs/python/_modules/mcap/mcap0/chunk_builder.html
- docs/python/_modules/mcap/mcap0/data_stream.html
- docs/python/_modules/mcap/mcap0/records.html
- docs/python/_modules/mcap/mcap0/opcode.html
\ninclude: []
